apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsimpleapps.example.com
spec:
  group: example.com
  names:
    kind: XSimpleApp
    plural: xsimpleapps
  claimNames:
    kind: SimpleApp
    plural: simpleapps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                parameters:
                  type: object
                  properties:
                    image:
                      type: string
                    replicas:
                      type: integer
                      default: 1
                      minimum: 1
                    port:
                      type: integer
                      default: 80
                    namespace:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
